##################################
#    SkinsRestorer Config.yml    #
#      Generated on ${version}       #
##################################
#
# We from SRTeam thank you for using our plugin!
# For more information        -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/
# For installation            -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Installing-SkinsRestorer
# For Configuration Help      -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Configuration
# Commands & Permissions      -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/cmds-&-perms
# For locale & messages       -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Locale-and-Translations
# Not working or get error?  -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Troubleshoot
# For advanced help or other, go to our Discord: https://discord.me/SkinsRestorer/

# (?) update config? -> https://raw.githubusercontent.com/SkinsRestorer/SkinsRestorerX/master/src/main/resources/config.yml
# (?) Step by step config guide -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Configuration

# (!) IF YOU USE BUNGEE, Check & set on every Spigot server spigot.yml -> bungeecord: true.  (!)
# (!) & Install Skinsrestorer.jar on ALL SERVERS!!! (BOTH Spigot & Bungeecord).              (!)

##########
# Basics #
##########

# Core features are here

# If true, players can change skins without permission.
# see https://github.com/SkinsRestorer/SkinsRestorerX/wiki/cmds-&-perms for perms.
SkinWithoutPerm: true

# Players cooldown when changing skins (set to 0 to disable).
# SkinErrorCooldown when a error or invalid url occurs.
# Can be bypassed with 'skinsrestorer.bypasscooldown'.
SkinChangeCooldown: 30
SkinErrorCooldown: 5

#################
# Customization #
#################

# Here you can design the plugin the way you want it.

# True will make use of the 'CUSTOM_HELP_IF_ENABLED' & `SR_LINE` in messages.yml.
# This is more customizable, but at the cost of permission specific help.
EnableCustomHelp: false

#Ignore messages.yml 'PREFIX ='
DisablePrefix: false

# Enable or disable default skins
# ApplyForPremium: false will only put a skin on skinless/steve players.
# If there is more than one, the plugin will choose a random one.
# [?] Supports custom & url.png skins, read SkinFile Generator below. [?]
# [!] url.png won't work on join for bungee, see https://github.com/SkinsRestorer/SkinsRestorerX/issues/315 [!]
DefaultSkins:
  Enabled: false
  ApplyForPremium: false
  Names:
    - "xknat"
    - "McLive"

# Skins in this list will be disabled, so users can't set them.
# Can be bypassed with 'skinsrestorer.bypassdisabled'.
DisabledSkins:
  Enabled: false
  Names:
    - "Steve"
    - "Owner"

# Custom list for the /skins GUI.
# ShowOnlyCustomGUI will only show CustomGUI.Names in the gui.
CustomGUI:
  Enabled: false
  ShowOnlyCustomGUI: true
  Names:
    - "xknat"
    - "McLive"

############
# Advanced #
############

# Below Config options are OPTIONAL and are irrelevant for small servers.

# Allows the usage of per-skin permission.
# Example: skinsrestorer.skin.xknat OR skinsrestorer.skin.McLive
# with "skinsrestorer.ownskin" you can set your own playername skin.
PerSkinPermissions: false

# Time that skins are stored in the database before we request again (in minutes).
SkinExpiresAfter: 15

# Multi-Bungee support
# Enable this if you have issues with skins in multi-proxy environments.
# (?) If you're using bungee and you have the plugin in all spigot servers and it still does not work, turn this on.
# (This is automatically enabled if you have RedisBungee)
MultiBungee:
  Enabled: false

# Settings for MySQL skin storage (recommended for big BungeeCord networks)
# [!] IF YOU USE BUNGEE, DO NOT ENABLE MYSQL in the Spigot / backend config.yml [!]
# [!] Non-root users: MySQL 8's new default authentication is not supported, use mysql_native_password [!]
MySQL:
  Enabled: false
  Host: localhost
  Port: 3306
  Database: db
  Username: root
  Password: pass
  SkinTable: 'Skins'
  PlayerTable: 'Players'
  ConnectionOptions: verifyServerCertificate=false&useSSL=false&serverTimezone=UTC

# Stop the process of setting a skin if the LoginEvent was canceled by an AntiBot plugin.
NoSkinIfLoginCanceled: true

# When enabled, Only websites from the list below is allowed to be set using /skin url <url>
RestrictSkinUrls:
  Enabled: false
  List:
    - https://i.imgur.com
    - http://i.imgur.com
    - https://storage.googleapis.com
    - http://storage.googleapis.com
    - https://cdn.discordapp.com
    - http://cdn.discordapp.com
    - https://textures.minecraft.net
    - http://textures.minecraft.net

# Here you can fill in your APIKey for lower MineSkin request times.
# Key can be requested from https://mineskin.org/apikey
# ((?) not needed for small servers / those not using the SkinUrl api (?))
MineskinAPIKey: "key"

#################
# Compatibility #
#################

# If we break things, you can disable it here.

# Dismounts a mounted (on a horse, or sitting) player when their skin is updated, preventing players from becoming desynced.
# File override = ./plugins/SkinsRestorer/disablesdismountplayer.txt
DismountPlayerOnSkinUpdate: true

# Remounts a player that was dismounted after a skin update (above option must be true).
# Disabling this is only recommended if you use plugins that allow you ride other players, or use sit. Otherwise you could get errors or players could be kicked for flying.
# File override = ./plugins/SkinsRestorer/disablesdismountplayer.txt
RemountPlayerOnSkinUpdate: true

# Dismounts all passengers mounting a player (such as plugins that let you ride another player), preventing those players from becoming desynced.
DismountPassengersOnSkinUpdate: false

###############
# Danger Zone #
###############

# ABSOLUTELY DO NOT CHANGE IF YOU DON'T KNOW WHAT YOU DO

# <!! Warning !!>
# Enabling this will stop SkinsRestorer to change skins on join.
# Handy for when you want run /skin apply to apply skin after texturepack popup
DisableOnJoinSkins: false

# <!! Warning !!>
# Enable this will require players to run "/skin update" to update their skin.
DisallowAutoUpdateSkin: false

# Updater Settings
Updater:
# # <!! Warning !!>
# Using outdated version void's support, compatibility & stability.
#
# To block all types of automatic updates (which can risk keeping a exploit):
# Create a file called 'noupdate.txt' in the plugin directory (./plugins/SkinsRestorer/ )

################
# DEV's corner #
################

# Enable these on the dev's request

# Enable to start receiving debug messages about api requests & more.
Debug: false

# End #

# Useful tools:
# Vectier Thailand has made some super cool "Custom Skin" tools that you can use!
#
# SkinFile Generator:
# With SkinFile Generator, you can upload your own custom skin to get a unique .skin file that you can put in your skins folder, to use with SkinsRestorer.
# Check it out here: https://riflowth.github.io/SkinFile-Generator/
#
# SkinSystem :
# With SkinSystem, you, as a server owner, can connect AuthMe (and forum) with the SkinSystem website that you can host, to give your players the ability to upload custom skins.
# Check it out here: https://github.com/riflowth/SkinSystem
#
# Useful Links #
# Website: https://skinsrestorer.net/
# Download: https://github.com/SkinsRestorer/SkinsRestorerX/releases
# Wiki https://github.com/SkinsRestorer/SkinsRestorerX/wiki/
# spigot: https://www.spigotmc.org/resources/skinsrestorer.2124/
# github: https://github.com/SkinsRestorer/SkinsRestorerX/
# discord: https://discord.me/SkinsRestorer/
