##############################
#  SkinsRestorer Config.yml  #
#  Generated on 13.8.4       #
##############################
#
# We from SRTeam thank you for using our plugin!
# For more information        -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/
# For installation            -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Installing-SkinsRestorer
# For Configuration Help      -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Configuration
# Commands & Permissions      -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/cmds-&-perms
# For locale & messages       -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Locale-and-Translations
# Not working or get error??  -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Troubleshoot
# For Advanced help or other go to our Discord: https://discord.me/SkinsRestorer/

# (?) Step by step config guide -> https://github.com/SkinsRestorer/SkinsRestorerX/wiki/Configuration

# (!) IF YOU USE BUNGEE, Check & set on every Spigot server spigot.yml -> bungeecord: true  (!)
# (!) & Install Skinsrestorer.jar on ALL SERVERS!!! (BOTH Spigot & Bungeecord)              (!)

  ##########
  # Basics #
  ##########

# If true, players can change skins without permission.
# see https://github.com/SkinsRestorer/SkinsRestorerX/wiki/cmds-&-perms for perms.
SkinWithoutPerm: true

# Players cooldown when changing skins (set to 0 to disable)
# SkinErrorCooldown when a error or invalid url occurs.
# Can be bypassed with 'skinsrestorer.bypasscooldown'
SkinChangeCooldown: 30
SkinErrorCooldown: 5

  #################
  # Customization #
  #################

# Enable or disable default skins
# ApplyForPremium: false will only put skin on skinless/steve players.
# If there is more than one, the plugin will choose a random one.
# [?] Does support Custom & url.png skin, read SkinFile Generator below [?]
# [!] url.png wont work on join for bungee, see https://github.com/SkinsRestorer/SkinsRestorerX/issues/315 [!]
DefaultSkins:
  Enabled: false
  ApplyForPremium: false
  Names:
    - xknat
    - McLive

# Skins in this list will be disabled, so users can't set it.
# Can by bypassed with 'skinsrestorer.bypassdisabled'
DisabledSkins:
  Enabled: false
  Names:
    - Steve
    - Owner

# Custom list for the /skins GUI.
# ShowOnlyCustomGUI will only show CustomGUI.Names in the gui
CustomGUI:
  Enabled: false
  ShowOnlyCustomGUI: true
  Names:
    - xknat
    - McLive

  ############
  # Advanced #
  ############

# Allows the usage of per skin perm.
# Example: skinsrestorer.skin.xknat OR skinsrestorer.skin.McLive
# with "skinsrestorer.ownskin" you can set your own playername skin.
PerSkinPermissions: false

# Time skins are stored in database before we request again (in minutes)
SkinExpiresAfter: 15

# Multi-Bungee support
# Enable this if you have issues with skins in multi-proxy environments
# If your using bungee and you have the plugin in all spigot servers and it still does not work, turn this on.
# (This is automatically enabled if you have RedisBungee)
MultiBungee:
  Enabled: false

# Settings for MySQL skin storage (recommended for big BungeeCord networks)
# [!] IF YOU USE BUNGEE, DO NOT ENABLE MYSQL in Spigot Config.yml [!]
# [!] non root users: MySQL 8's new default authentication is not supported, use mysql_native_password [!]
MySQL:
  Enabled: false
  Host: localhost
  Port: 3306
  Database: db
  Username: root
  Password: pass
  SkinTable: 'Skins'
  PlayerTable: 'Players'
  ConnectionOptions: verifyServerCertificate=false&useSSL=false&serverTimezone=UTC

# <!! Warning !!>
# Enabling this will stop SkinsRestorer to change skins on join.
DisableOnJoinSkins: false

# Enable or disable the updater.
Updater:
  Enabled: true
  PeriodicChecks: true

# Stop the process of setting a skin if the LoginEvent was canceled by an AntiBot plugin
NoSkinIfLoginCanceled: true

  #################
  # Compatibility #
  #################

# True will again make use of the 'HELP_PLAYER' & `SR_LINE` in messages.yml
# This is more customizable, but at the cost of permission specific help.
UseOldSkinHelp: false

#Ignore messages.yml 'PREFIX ='
DisablePrefix: false

  ################
  # DEV's corner #
  ################

# Enable to start receiving debug messages about api request & more.
Debug: false

# WIP WONT WORK
# Set the language you will use - Files are located in /SkinsRestorer/languages directory
# You can add custom locale file by copying the english.yml, renaming the new file into your language and editing it
# Default: english - english.yml
Locale: english
# ^ WONT WORK YET!


# End #

# Useful tools:
# Vectier Thailand has made some super cool "Custom Skin" tools that you can use!
#
# SkinFile Generator:
# With SkinFile Generator you can upload your own custom skin to get a unique .skin file that you can put in your skins folder to use with SkinsRestorer.
# Check it out here: https://riflowth.github.io/SkinFile-Generator/
#
# SkinSystem :
# With SkinSystem you as a server owner can connect AuthMe (and forum) with the SkinSystem website that you can host to give your players the ability to upload custom skins.
# Check it out here: https://github.com/riflowth/SkinSystem
#
# Useful Links #
# Website: https://skinsrestorer.net/
# Download: https://github.com/SkinsRestorer/SkinsRestorerX/releases
# Wiki https://github.com/SkinsRestorer/SkinsRestorerX/wiki/
# spigot: https://www.spigotmc.org/resources/skinsrestorer.2124/
# github: https://github.com/SkinsRestorer/SkinsRestorerX/
# discord: https://discord.me/SkinsRestorer/