metadata.format.version = "1.1"

[versions]

runtask = "2.2.2"
runpaperversion = "1.20.2"
runwaterfallversion = "1.19"
runvelocityversion = "3.2.0-SNAPSHOT"

[libraries]

[plugins]

runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }
runwaterfall = { id = "xyz.jpenilla.run-waterfall", version.ref = "runtask" }
